# Analytics Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  namespace: url-shortener
  labels:
    app: analytics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: analytics:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3003
          env:
            - name: MONGO_URI
              value: mongodb://mongodb-service:27017/urlshortener
            - name: PORT
              value: "3003"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 30
            periodSeconds: 10
---
# Analytics Service
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: url-shortener
spec:
  selector:
    app: analytics
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
  type: ClusterIP
