# Redirect Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirect
  namespace: url-shortener
  labels:
    app: redirect
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redirect
  template:
    metadata:
      labels:
        app: redirect
    spec:
      containers:
        - name: redirect
          image: redirect:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
          env:
            - name: MONGO_URI
              value: mongodb://mongodb-service:27017/urlshortener
            - name: ANALYTICS_SERVICE_URL
              value: http://analytics-service:3003
            - name: PORT
              value: "3002"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 10
---
# Redirect Service
apiVersion: v1
kind: Service
metadata:
  name: redirect-service
  namespace: url-shortener
spec:
  selector:
    app: redirect
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
  type: LoadBalancer
