apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortener
  namespace: url-shortener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shortener
  template:
    metadata:
      labels:
        app: shortener
    spec:
      containers:
      - name: shortener
        image: shortener:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URI
          value: mongodb://mongodb-service:27017/urlshortener
        - name: BASE_URL
          value: http://localhost:3002
        - name: PORT
          value: "3001"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: shortener-service
  namespace: url-shortener
spec:
  selector:
    app: shortener
  ports:
  - port: 3001
    targetPort: 3001
  type: LoadBalancer